export const USERS_LIST_INIT = "USERS_LIST_INIT";
export const USERS_LIST_COMPLETE = "USERS_LIST_COMPLETE";
export const USERS_LIST_ERROR = "USERS_LIST_ERROR";

export const USERS_DETAIL_INIT = "USERS_DETAIL_INIT";
export const USERS_DETAIL_COMPLETE = "USERS_DETAIL_COMPLETE";
export const USERS_DETAIL_ERROR = "USERS_DETAIL_ERROR";

export const USERS_SEARCH_INIT = "USERS_SEARCH_INIT";

export const USERS_FOLLOWERS_INIT = "USERS_FOLLOWERS_INIT";
export const USERS_FOLLOWERS_COMPLETE = "USERS_FOLLOWERS_COMPLETE";
